name: Simplified Deployment Workflow

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main branch

jobs:
  deploy-to-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://example.com/staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Deployment to Staging
        run: echo "Deploying to staging environment..."

  deploy-to-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    environment:
      name: production
      url: https://example.com/production

    steps:
      - name: Simulate Deployment to Production
        run: echo "Deploying to production environment..."
